# fly.toml app configuration file generated for sgar-api on 2023-10-29T20:10:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sgar-api"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
